### ISSUE TITLE
Show Company Name in header

### ISSUE THREAD

**Issue by caprenter** [Bjwebb/bookish#39]
I think might be useful. 

How do I get this into the header tho. Do I need to use template tags?
https://docs.djangoproject.com/en/dev/howto/custom-template-tags/

**Comment by Bjwebb** [comment]
No, I don't think you'll need template tag. Instead we want to pass in the company name in the context from the view. Currently we aren't passing around any information about what company we're looking at. Since some users can see multiple companies we probably want to add the company UUID to the urls. We should be able to add this functionality to one new class, and then inherit it. @caprenter Do you want to have a go at this, or should I implement it?

**Comment by caprenter** [comment]
I'm happy to have a go

**Comment by caprenter** [comment]
Tried. Failed. Giving up. Going swimming! Any hints?

**Comment by Bjwebb** [comment]
I can't think of any obvious hints without seeing what you tried doing.
